
# Preview of the minepkg.toml format! Could break anytime!
manifestVersion = 0

[package]
  type = "mod"
  name = "minepkg-companion"
  description = "A helper mod for minepkg. It would be lonely without it."
  version = "0.7.1"
  platform = "fabric"
  license = "MIT"

# These are global requirements
[requirements]
  minecraft = "~1.17.0-0 || ~1.18.0-0 || ~1.19.0-0 || ~1.20.0-0 || ~1.21.0-0"
  fabricLoader = "*"
  minepkgCompanion = "none"

[dependencies]

[dev]
  buildCommand = "./gradlew build"

  [dev.dependencies]
    #fabric = "*"
