# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build jar then crash test

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: 21
      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4 
        with:
          name: jars
          path: build/libs
      - name: Cleanup Gradle Cache
        # Remove some files from the Gradle cache, so they aren't cached by GitHub Actions.
        # Restoring these files from a GitHub Actions cache might cause problems for future builds.
        run: |
          rm -f ~/.gradle/caches/modules-2/modules-2.lock
          rm -f ~/.gradle/caches/modules-2/gc.properties

  # crash test jobs runs after build (because of `needs: build`) and uses its artifacts
  crash-test:
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        minecraft:
          [
            1.16.0,
            1.16.1,
            1.16.2,
            1.16.3,
            1.16.4,
            1.16.5,
            1.17.0,
            1.17.1,
            1.18.0,
            1.18.1,
            1.18.2,
            1.19.0,
            1.19.1,
            1.19.2,
            1.19.3,
            1.19.4,
            1.20.0,
            1.20.1,
            1.20.2,
            1.20.3,
            1.20.4,
            1.20.5,
            1.20.6,
            1.21.0,
            1.21.1,
            1.21.2,
            1.21.3,
            1.21.4,
            1.21.5
          ]
    steps:
      - uses: actions/checkout@v4
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: jars
          path: build/libs
      - uses: minepkg/action-crash-test@v0
        with:
          minecraft: ${{ matrix.minecraft }}
          no-build: true